      "sudo kubeadm config print init-defaults | tee ClusterConfiguration.yaml",
      "sudo sed -i '/name/d' ClusterConfiguration.yaml",
      "sudo sed -i 's/ advertiseAddress: 1.2.3.4/ advertiseAddress: ${vsphere_virtual_machine.vm.default_ip_address}/' ClusterConfiguration.yaml",
      "sudo sed -i 's/ criSocket: \\/var\\/run\\/dockershim\\.sock/ criSocket: \\/run\\/containerd\\/containerd\\.sock/' ClusterConfiguration.yaml",
      "sudo cat << EOF | cat >> ClusterConfiguration.yaml",
      "--",
      "apiVersion: kubelet.config.k8s.io/v1beta1",
      "kind: KubeletConfiguration",
      "cgroupDriver: systemd",
      "EOF",
      "sudo kubeadm init --config=ClusterConfiguration.yaml",
      "mkdir -p $HOME/.kube",
      "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config",
      "sudo chown $(id -u):$(id -g) $HOME/.kube/config",
      "kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml",
      "kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml",